// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3A4MuQ9aSyc5tKyR9l-QY8SDIw3WehwY',
    appId: '1:591218284989:web:81690debc2c23e69f55ad4',
    messagingSenderId: '591218284989',
    projectId: 'buddyregistrationwithux',
    authDomain: 'buddyregistrationwithux.firebaseapp.com',
    storageBucket: 'buddyregistrationwithux.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2yzoDUyovWFhCLiNy47jFEf0N0aB2Qw',
    appId: '1:591218284989:android:81119ec047d8c5c7f55ad4',
    messagingSenderId: '591218284989',
    projectId: 'buddyregistrationwithux',
    storageBucket: 'buddyregistrationwithux.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkF-wYfcBP4NW8k-TJ7iAp0QqodrEYLU',
    appId: '1:591218284989:ios:7b14ebd0c949ae7ff55ad4',
    messagingSenderId: '591218284989',
    projectId: 'buddyregistrationwithux',
    storageBucket: 'buddyregistrationwithux.appspot.com',
    iosClientId: '591218284989-69ave3mlrbn9bdr197qol9upc2rl3psh.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddysigninwithui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkF-wYfcBP4NW8k-TJ7iAp0QqodrEYLU',
    appId: '1:591218284989:ios:fc2bc539e417715af55ad4',
    messagingSenderId: '591218284989',
    projectId: 'buddyregistrationwithux',
    storageBucket: 'buddyregistrationwithux.appspot.com',
    iosClientId: '591218284989-l3sgnkh93k4ubee94mt4a3ejgp7a2664.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddysigninwithui.RunnerTests',
  );
}
